# Generated by Django 2.2.6 on 2019-10-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.URLField(default='https://cdn4.iconfinder.com/data/icons/political-elections/50/48-512.png'),
        ),
    ]
