# Generated by Django 2.2.6 on 2019-10-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191016_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.URLField(blank=True, default='https://cdn4.iconfinder.com/data/icons/political-elections/50/48-512.png', null=True),
        ),
    ]
