# Generated by Django 2.2.6 on 2019-10-19 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_midorder_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MidOrder',
            new_name='ItemOrder',
        ),
    ]
