# Generated by Django 2.2.6 on 2019-10-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20191020_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorder',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
