# Generated by Django 2.2.6 on 2019-10-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_itemorder_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemorder',
            name='total',
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
