# Generated by Django 2.2.6 on 2019-10-22 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20191021_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
    ]
